--- # This is structural YAML example to install HTTPD on Centos 7

- hosts: {{ webserver }}
  become_method: sudo
  connection: ssh
  become: yes
  gather_facts: no
  
  roles:
    - apache_invokedockercompose
