--- # install basic packages

#- name: apt-get update the server
#  apt:
#   update_cache=yes

- name: Install packages build-essential and libssl-dev
  apt: name={{ item }} state=latest
  with_items:
   - build-essential
   - libssl-dev

- name: Check if Node installed
  register: node_installed
  command: node -v
  ignore_errors: true

- name: Downlaod node install file
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh dest=/tmp/install.sh
  when: node_installed|failed


- name: Run Node install script
  raw: chmod +x /tmp/install.sh ; sh /tmp/install.sh
  when: node_installed|failed

- name: Install node {{ nodeversion }}
  sudo: no
  shell: export NVM_DIR="/root/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm install {{ nodejs_version }} && nvm use {{ nodejs_version }} && nvm alias default {{ nodejs_version }}
  when: node_installed|failed
