---
    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
          name: my_keypair
      register: my_keypair

    - name: save key pair on localhost
      copy:
        content: "{{ my_keypair }}"
        dest: templates/my_keypair.pem

    - name: Create a security group
      ec2_group:
        name: "my_sg"
        description: The webservers security group
        region: "us-west-2"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
    - name: Launching an EC2 Instance hostname MSR-test-Instance-1
      ec2:
        instance_type : "{{ instance_type }}"
        image: "{{ imageid }}"
        region: "us-west-2"
        keypair: "my_keypair"
        count: 1
        group: "my_sg"
        instance_tags:
          Name: "{{ host1 }}"
        wait: true
        #assign_public_ip: yes

    - name: Launching an EC2 Instance hostname MSR-test-Instance-2
      ec2:
        instance_type : "{{ instance_type }}"
        image: "{{ imageid }}"
        region: "us-west-2"
        keypair: "my_keypair"
        count: 1
        group: "my_sg"
        instance_tags:
            Name: "{{ host2 }}"
        wait: true
        #assign_public_ip: yes
